---
- include_tasks: "elastic_ilm_policy_template.yml"
  when: ilm_policy_file_location is defined and ilm_policy_filename is defined and ilm_policy is defined

- block:
  - name: Update policy and template when not upgrading
    include_tasks: "elastic_ilm_update_policy.yml"
  delegate_to: "{{ groups['elastic-logstash'][0] }}"
  environment:
    no_proxy: "{{ hostvars[groups['elastic-logstash'][0]]['ansible_host'] }},127.0.0.1"
  run_once: True
  when: (elk_package_state | default('present')) != "latest"
